version: 2

updates:
  - package-ecosystem: npm
    directories:
      - /
      - /examples/vanilla
      - /examples/react
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Madrid
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:15"
      timezone: Europe/Madrid
    open-pull-requests-limit: 3
