import React from 'react';
import {
  BadgeEuro,
  BarChart3,
  Binary,
  Braces,
  Calculator,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  CaseUpper,
  CircleUserRound,
  Clock3,
  Crop,
  FileArchive,
  FileImage,
  FilePenLine,
  FileSpreadsheet,
  FileText,
  Files,
  GitCompareArrows,
  Image,
  ImageDown,
  KeyRound,
  Link2,
  ListChecks,
  LockKeyhole,
  PackageCheck,
  PanelTop,
  Percent,
  Phone,
  QrCode,
  ReceiptText,
  RefreshCw,
  RotateCw,
  ScanLine,
  Scissors,
  ShieldCheck,
  Signature,
  SlidersHorizontal,
  Sparkles,
  Table2,
  Tags,
  Timer,
  Type,
  UserRoundCheck,
  WalletCards,
  WandSparkles,
  Wrench,
} from 'lucide-react';

export const categoryIcons = {
  pdf: FileText,
  'image-editing': Image,
  'image-portals': ScanLine,
  data: Braces,
  text: Type,
  business: BadgeEuro,
  math: Calculator,
  'productivity-security': ShieldCheck,
  media: FileImage,
  'guest-operations': CalendarDays,
  'housekeeping-maintenance': Wrench,
  'revenue-finance': BarChart3,
  'data-operations': FileSpreadsheet,
  'content-privacy': LockKeyhole,
};

const exactIcons = {
  'sign-pdf': Signature,
  'merge-pdf': Files,
  'delete-pdf-pages': FileText,
  'compress-pdf': FileArchive,
  'split-pdf': Scissors,
  'rotate-pdf': RotateCw,
  'pdf-to-word': FileText,
  'pdf-to-jpg': FileImage,
  'jpg-to-pdf': FileText,
  'compress-image': ImageDown,
  'resize-image': Crop,
  'crop-image-circle': CircleUserRound,
  'heic-to-jpg': RefreshCw,
  'webp-to-png': RefreshCw,
  'png-to-jpg': RefreshCw,
  'jpg-to-png': RefreshCw,
  'json-formatter': Braces,
  'json-to-csv': Table2,
  base64: Binary,
  'unix-timestamp': Clock3,
  'word-counter': Type,
  'case-converter': CaseUpper,
  'text-diff-checker': GitCompareArrows,
  'vat-calculator': ReceiptText,
  'business-days-calculator': CalendarDays,
  'discount-calculator': Tags,
  'age-calculator': CircleUserRound,
  'currency-converter': BadgeEuro,
  'rule-of-three-calculator': Percent,
  calculator: Calculator,
  'percentage-calculator': Percent,
  'unit-converter': SlidersHorizontal,
  'password-gen': KeyRound,
  'qr-generator': QrCode,
  timer: Timer,
  'stay-nights-calculator': CalendarClock,
  'booking-balance-calculator': WalletCards,
  'cancellation-window-calculator': CalendarDays,
  'tent-capacity-planner': UserRoundCheck,
  'arrival-departure-board': ListChecks,
  'international-phone-whatsapp-link': Phone,
  'reservation-to-ics': CalendarPlus,
  'turnover-workload-planner': RefreshCw,
  'linen-amenities-calculator': PackageCheck,
  'stock-reorder-calculator': PackageCheck,
  'maintenance-incident-report': FilePenLine,
  'hospitality-kpi-calculator': BarChart3,
  'channel-commission-calculator': BadgeEuro,
  'promotion-margin-calculator': Percent,
  'reservation-csv-cleaner': WandSparkles,
  'duplicate-booking-detector': GitCompareArrows,
  'booking-data-redactor': ShieldCheck,
  'image-metadata-remover': LockKeyhole,
  'incident-photo-preparer': ImageDown,
  'utm-link-builder': Link2,
  'redact-pdf': ShieldCheck,
  'ocr-searchable-pdf': ScanLine,
  'sanitize-flatten-pdf': LockKeyhole,
  'watermark-pdf': FilePenLine,
  'number-pdf-pages': ListChecks,
  'protect-unlock-pdf': LockKeyhole,
  'pdf-table-extractor': Table2,
  'image-visual-redactor': LockKeyhole,
  'remove-image-background': WandSparkles,
  'screen-recorder': PanelTop,
  'video-share-preparer': FileImage,
  'voice-audio-cleaner': SlidersHorizontal,
  'zip-archive-manager': FileArchive,
  'file-hash-checksum': Binary,
  'email-header-analyzer': ShieldCheck,
};

export function ToolIcon({ tool, size = 22 }) {
  let Icon = exactIcons[tool.id] || categoryIcons[tool.category] || Sparkles;

  if (tool.id.startsWith('compress-image-to-')) Icon = ImageDown;

  return <Icon size={size} strokeWidth={1.9} aria-hidden="true" />;
}

export function CategoryIcon({ categoryId, size = 18 }) {
  const Icon = categoryIcons[categoryId] || PanelTop;
  return <Icon size={size} strokeWidth={1.9} aria-hidden="true" />;
}
